### ISSUE TITLE
gracefull exit?

### ISSUE THREAD

**Issue by vearne** [rfyiamcool/cronlib#3]
It looks like when call CronSchduler.Stop() ,some job may still running

**Comment by zplzpl** [comment]
CronSchduler.Join() ，It will wait for all job models to exit

**Comment by zplzpl** [comment]
Join 更适合换成 Wait

**Comment by zplzpl** [comment]
Join的命名不能直接理解，建议换成Wait  @rfyiamcool

**Comment by rfyiamcool** [comment]
可以 @zplzpl
