### ISSUE TITLE
timer stop

### ISSUE THREAD

**Issue by zplzpl** [rfyiamcool/cronlib#4]
https://github.com/rfyiamcool/cronlib/blob/master/scheduler.go#L339

timer没有进行stop操作，这个出于什么考虑？

**Comment by rfyiamcool** [comment]
😅 这个是我漏掉了，虽然没有stop，但是不会造成泄露的。

**Comment by rfyiamcool** [comment]
已经修正，thanks 

https://github.com/rfyiamcool/cronlib/commit/e596616eb4c020b6deb11e5d2b9b9f6eeeb6c6e1
