### ISSUE TITLE
dynamic add job but not run 

### ISSUE THREAD

**Issue by atdevp** [rfyiamcool/cronlib#5]
My sample code:

func RegisterCrontabController(c *gin.Context) {
	var inputs APIRegisterCrontab
	if err := c.Bind(&inputs); err != nil {
		h.RespondHandler(400, err.Error(), c, "")
		return
	}

	spec := inputs.SchedueTime
	log.Println(spec, inputs.Guid)
	// */2 * * * * *  biq5i2ickkuogr133b6g-1555323146
	cron := g.CrontabSet.Get()
	f := func() {
		log.Println("新增的任务,等待管理员分配机器~")
	}
	job, err := cronlib.NewJobModel(spec, f)
	if err != nil {
		msg := fmt.Sprintf("init new job model failed: %s", err.Error())
		log.Printf(msg)
		h.RespondHandler(400, msg, c, "")
		return
	}
	err = cron.Register(inputs.Guid, job)
	if err != nil {
		msg := fmt.Sprintf("register failed: %s", err.Error())
		log.Println(msg)
		h.RespondHandler(400, msg, c, "")
		return
	}
	msg := fmt.Sprintf("agent execute register job success")
	log.Println(msg)
	h.RespondHandler(200, msg, c, "")
	return
}

**Comment by rfyiamcool** [comment]
动态注册是没问题的，可以看下 example/run.go# dynamic add job test
