### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by myml** [rfyiamcool/cronlib#9]
Is the project open source? Can you add an open source license file?

**Comment by myml** [comment]
@rfyiamcool

**Comment by rfyiamcool** [comment]
没这么多讲究，直接用就行了。😅

**Comment by myml** [comment]
不加授权协议，一般会认为不开源，这不利于项目的推广和使用...

fengyun.rui ***@***.***> 于2021年9月27日周一 下午3:11写道：

**Comment by rfyiamcool** [comment]
哈哈，好 @myml
